// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package queries

import (
	"time"
)

type Blog struct {
	ID         int64
	Title      string
	Content    string
	CreateDate time.Time
}

type ChatHistory struct {
	ID         int64
	Sender     string
	Message    string
	CreateDate time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
}
