basePath: /v1
definitions:
  blog.Post:
    properties:
      content:
        type: string
      create_date:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
host: api.freejing.com
info:
  contact:
    email: Andrewjeremy12345@gmail.com
    name: Andrew Jeremy
  description: 'This API is a self-made project made with golang, this repository
    can be accessed on: https://github.com/FreeJ1nG/freejing-be'
  title: FreeJinG API
  version: "1.0"
paths:
  /blogs:
    post:
      consumes:
      - application/json
      description: Create new blog post
      parameters:
      - description: Create Blog Post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/blog.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blog.Post'
      summary: Create new blog post
      tags:
      - blog
swagger: "2.0"
