// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package dbquery

import (
	"time"
)

type Blog struct {
	ID         int64 `json:"id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	CreateDate time.Time `json:"create_date"`
}

type ChatHistory struct {
	ID         int64 `json:"id"`
	Sender     string `json:"sender"`
	Message    string `json:"message"`
	CreateDate time.Time `json:"create_date"`
}

type User struct {
	ID           int64 `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordhash`
}
